<h2>Please, sign in using this form</h2>

<?php echo $this->tag->form("index/login"); ?>
 <p>
    <label for="email">E-Mail</label>
    <?php echo $this->tag->emailField("email") ?>
 </p>
 
 <p>
    <label for="name">Password</label>
    <?php echo $this->tag->passwordField("password") ?>
 </p>

 <p>
    <?php echo $this->tag->submitButton("Log in") ?>
 </p>

</form>
<?php 
    echo $this->tag->linkTo("signup", "Sign Up Here!");
?>